FROM intel/intel-extension-for-pytorch:2.1.10-xpu
USER root
RUN apt-get update
RUN apt-get install -y ninja-build intel-oneapi-dpcpp-cpp-2024.0 intel-oneapi-dnnl-devel-2024.0 intel-oneapi-mkl-devel-2024.0 python3-dev
